-- Fill testdata 
SOURCE ./dml/employee.sql
SOURCE ./dml/patient.sql
SOURCE ./dml/doctor.sql
SOURCE ./dml/orthoptist.sql
SOURCE ./dml/receptionist.sql
SOURCE ./dml/insurance.sql
SOURCE ./dml/patient_insurance.sql
SOURCE ./dml/drug.sql
SOURCE ./dml/user.sql
SOURCE ./dml/calendarentry.sql
SOURCE ./dml/appointment.sql
SOURCE ./dml/anamnesis.sql
SOURCE ./dml/queue.sql
SOURCE ./dml/queue_employee.sql
SOURCE ./dml/queueentry.sql
SOURCE ./dml/disease.sql
SOURCE ./dml/diagnosis.sql
SOURCE ./dml/drugintolerance.sql
SOURCE ./dml/servicecode.sql
